#!/usr/bin/env bash
# shellcheck source=/dev/null
source /usr/lib/bashio/bashio.sh

bashio::log.info "Stopping Ollama server..."

pkill -TERM -x ollama 2>/dev/null || true
sleep 5

bashio::log.info "Ollama stopped."
